### ISSUE TITLE
BigSnooze

### ISSUE THREAD

**Issue by btfls** [ca13ra1/bigsnooze-bugs#1]
**Describe the bug**
Hi, be just purchased BigSnooze tweak but it doesn’t install correctly, no icon created in setup ang no way to configure it. I installed, run iCleaner pro and reinstalled but happens the same.
I’ve an iPhone X with iOS 13.5 in uncover 5.3.1
Email: fcolorspe@gmail.com
Regards
Francisco Lorenzo

**Comment by ca13ra1** [comment]
There’s no options to configure. It supports, iOS 13 for sure. Have you figured out the issue?

**Comment by ca13ra1** [comment]
Closing issue, most likely relating to the jailbreak used.
